[versions]
junit-jupiter = "5.11.0"
picocli = "4.7.6"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
